### PR TITLE
cmd/pomerium: exit 0 for normal shutdown

### LINKED ISSUE #1935: Exit service results in fatal error
## What happened?
When one is breaking the running application it shuts down with an error which causes services such as systemd to set the application as failed.

I have observed this with both memory and redis datastorage.

## What did you expect to happen?
Application should exit cleanly

## How'd it happen?

1. Ran `pomerium -config config.yaml`
2. Break with `Ctrl + c`
3. Saw error `{"level":"fatal","error":"context canceled","time":"2021-02-23T07:45:47Z","message":"cmd/pomerium"}`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.12.1-1611179121+77abb53
- Server Operating System/Architecture/Cloud: Ubuntu 18.04 (4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

## What's your config.yaml?

```config.yaml
address: :443
metrics_address: :9299

authenticate_service_url: https://authenticate.example.com

certificates:
   - cert: /etc/pomerium/fullchain.pem
     key: /etc/pomerium/privkey.pem

cookie_secret: "REDACTED"

# IDP configuration
idp_provider: "google"
idp_client_id: "REDACTED"
idp_client_secret: "REDACTED"
idp_service_account: "REDACTED"

jwt_claims_headers: "user,email,groups"

policy:
  - from: https://app.example.com
    to: http://internal.server
    pass_identity_headers: true
    preserve_host_header: true
    allowed_domains:
            - example.com
```

## What did you see in the logs?

```logs
 ^C{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"fatal","error":"context canceled","time":"2021-02-23T07:45:47Z","message":"cmd/pomerium"}
```

### PR DESCRIPTION
**Pull request by travisgroth**
## Summary
Right now we hit a `Fatal()` log statement for any error reason at exit, including context cancellation resulting from various OS signals.  This results in a non-zero exit code even when the termination was requested gracefully.

This PR checks if the underlying error is a `context.Canceled` and will exit normally in that case.  This should cover most normal shutdowns such as SIGTERM.

## Related issues

Fixes #1935 

## Checklist

- [x] reference any related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

File: cmd/pomerium/main.go [hunk 1]
```diff
@@ -16,9 +17,10 @@ var (
 )
 
 func main() {
-	if err := run(context.Background()); err != nil {
+	if err := run(context.Background()); !errors.Is(err, context.Canceled) {
```
Comment (travisgroth) [inline cmd/pomerium/main.go:20]: I think this could be more sophisticated by only catching certain signals, but I'm not sure it's worth the complexity.

**Review by calebdoxsey — APPROVED** [review]
