### PR TITLE
okta: handle deleted groups

### LINKED ISSUE #1414: 0.10.3 identity_manager unable to pull groups from Okta directory if malformed user entry exists
## What happened?

Upgraded to Pomerium v10 from v9 and not group information is available for use in policies.

## What did you expect to happen?

Okta groups available for use in policies.

## What's your environment like?

- 0.10.3:
- Kubernetes / v1.16.13-eks-2ba888

## What's your config.yaml?

```config.yaml
address: :443
grpc_address: :443
certificate_file: /pomerium/cert.pem
certificate_key_file: /pomerium/privkey.pem
certificate_authority_file: /pomerium/ca.pem
authenticate_service_url: https://auth.<domain>
authorize_service_url: https://pomerium-authorize.pomerium.svc.cluster.local
cache_service_url: https://pomerium-cache.pomerium.svc.cluster.local
idp_provider: okta
idp_scopes: null
idp_provider_url: https://<domain>.okta.com
insecure_server: false
grpc_insecure: false
metrics_address: :9090
forward_auth_url: https://fwdauth.<domain>
# Randomly generated 32 byte base64 encoded value
cookie_secret: <sensitive>
# Randomly generated 32 byte base64 encoded value
shared_secret: <sensitive>
# okta application client id
idp_client_id: <sensitive>
# okta application client secret
idp_client_secret: <sensitive>
# okta access token (json | base64 -w0)
idp_service_account: <sensitive>
# https://www.pomerium.io/reference/#identity-provider-refresh-directory-settings
idp_refresh_directory_interval: 15m
idp_refresh_directory_timeout: 10m
```

## What did you see in the logs?

```logs
{"level":"info","service":"identity_manager","time":"2020-09-17T12:54:22Z","message":"refreshing directory users"}
{"level":"info","service":"directory","provider":"okta","time":"2020-09-17T12:54:22Z","message":"getting user groups"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:22Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:23Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:23Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:23Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/user.User","id":"okta/00u14szxczGdVZZZq2p7","time":"2020-09-17T12:54:23Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/directory.User","id":"okta/00u14szxczGdVZZZq2p7","time":"2020-09-17T12:54:23Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:31Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:31Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/user.User","id":"okta/00u14szxczGdVZZZq2p7","time":"2020-09-17T12:54:31Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/directory.User","id":"okta/00u14szxczGdVZZZq2p7","time":"2020-09-17T12:54:31Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:32Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"ID.CD7M3GdGDoqLtoGqE8NaAgohH03JBVsI9GoZtozl3Ss","time":"2020-09-17T12:54:32Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/user.User","id":"okta/00u14szxczGdVZZZq2p7","time":"2020-09-17T12:54:32Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/directory.User","id":"okta/00u14szxczGdVZZZq2p7","time":"2020-09-17T12:54:32Z","message":"get"}
{"level":"warn","service":"identity_manager","error":"okta: error querying for groups: okta: error query api status_code=404: {\"errorCode\":\"E0000007\",\"errorSummary\":\"Not found: Resource not found: 00g8c2un87WlACA102p7 (UserGroup)\",\"errorLink\":\"E0000007\",\"errorId\":\"oaeYN5QlQLCSqmmgELo-Qiwig\",\"errorCauses\":[]}","time":"2020-09-17T12:55:41Z","message":"failed to refresh directory users and groups"}
```

## Additional context

I'm not sure how to get debug logs from cache service in regards to which UserGroup it is trying to pull to take a look at that record in the directory.

### PR DESCRIPTION
**Pull request by calebdoxsey**
## Summary
We rely on a local cache of groups to improve the efficiency of the Okta API. Unfortunately we were never removing groups from this cache, so if a group was deleted we would still query for its members and that call would fail.

This PR adds a check for a 404 on the members call and if received deletes the local group and ignores the error.

## Related issues
Fixes #1414 

**Checklist**:
- [x] add related issues
- [ ] updated docs
- [x] updated unit tests
- [ ] updated UPGRADING.md
- [x] ready for review

### CODE REVIEW

File: internal/directory/okta/okta.go [hunk 1]
```diff
@@ -278,3 +291,32 @@ func ParseServiceAccount(rawServiceAccount string) (*ServiceAccount, error) {
...
+	ErrorLink      string   `json:"errorLink"`
+	ErrorID        string   `json:"errorId"`
+	ErrorCauses    []string `json:"errorCauses"`
+}
+
+func newAPIError(res *http.Response) error {
+	if res == nil {
+		return nil
+	}
+	buf, _ := ioutil.ReadAll(res.Body)
```
Comment (desimone) [inline internal/directory/okta/okta.go:310]: Pure paranoid but... should we implement `io.LimitReader` on this just in case?

**Review by desimone — APPROVED** [review]
