### PR TITLE
xds: fix always requiring client certificates

### LINKED ISSUE #1843: Pomerium always asks for client certificates
## What happened?
Due to a recent change (#1835), Pomerium now appears to always ask for client certificates, even if they aren't actually used. Although it allows access if one is not provided, it should only be asking when necessary.

## What did you expect to happen?
Not to be prompted to provide a client certificate.

## How'd it happen?
1. Install a client certificate in your browser
2. Access a route with no client certificate required
3. Saw the prompt to pick a client certificate

## What's your environment like?
- Pomerium version: git master (5558f81ffcf1c1390979ffa78163ab4b3e00875f)
- Server Operating System/Architecture/Cloud: linux, amd64, native

## What's your config.yaml?
Should happen for any route.

## Additional context
The likely fix here is to only add a validation context to `envoy_extensions_transport_sockets_tls_v3.CommonTlsContext` when necessary.

### PR DESCRIPTION
**Pull request by calebdoxsey**
## Summary
In https://github.com/pomerium/pomerium/pull/1835 I accidentally ended up requiring client certificates for any route Pomerium handled. Although this doesn't break anything, since it still allows access even if you don't provide one, it's pretty annoying to have to pick one.

This PR updates the validation context so that it's only added if we are using `ClientCA` or `TLSDownstreamClientCA` for a particular domain.

## Related issues
Fixes #1843 

## Checklist
- [x] reference any related issues
- [ ] updated docs
- [x] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

File: internal/controlplane/xds_listeners.go [hunk 1]
```diff
@@ -633,3 +626,40 @@ func hostMatchesDomain(u *url.URL, host string) bool {
...
+	domain string,
+) *envoy_extensions_transport_sockets_tls_v3.CommonTlsContext_ValidationContext {
+	needsClientCert := false
+
+	if cfg.Options.ClientCA != "" {
+		needsClientCert = true
+	}
+	for _, p := range getPoliciesForDomain(cfg.Options, domain) {
+		if p.TLSDownstreamClientCA != "" {
+			needsClientCert = true
```
Comment (desimone) [inline internal/controlplane/xds_listeners.go:641]: break early on find?

File: internal/controlplane/xds_listeners.go [hunk 2]
```diff
@@ -633,3 +626,40 @@ func hostMatchesDomain(u *url.URL, host string) bool {
...
+func getDownstreamValidationContext(
+	cfg *config.Config,
+	domain string,
+) *envoy_extensions_transport_sockets_tls_v3.CommonTlsContext_ValidationContext {
+	needsClientCert := false
+
+	if cfg.Options.ClientCA != "" {
+		needsClientCert = true
+	}
+	for _, p := range getPoliciesForDomain(cfg.Options, domain) {
```
Comment (desimone) [inline internal/controlplane/xds_listeners.go:639]: if `needsClientCert == true`, skip loop?

**Review by desimone — APPROVED** [review]
LGTM, a few tiny over-optimization suggestions.

**Review by desimone — APPROVED** [review]
