### PR TITLE
internal/httputil: use error structs for http errors

### LINKED ISSUE #157: "Troubleshoot your session" link broken when on authenticate error page
**Describe the bug**

When facing the error in #152 with latest pomerium, the error page show:
image

With the link pointing to `https://auth.aks.xxx.com/.pomerium` (cf #152 for the detailed configuration).

When I click on the link, I see a 404 error page.

Logs of authenticate service:
```json
{"level":"debug","fwd_ip":"10.240.0.35","ip":"10.240.0.61","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0","referer":"https://auth.aks.xxx.com/sign_in?redirect_uri=https%3A%2F%2Fapp.xxx.com%2F.pomerium%2Fcallback&response_type=code&shared_secret=ZGhZZ09KVnlrK1JKMEMrbTAwSDZ5TVBNNFRkZko5dnc%3D&sig=fwY4hecOamSsMVAi-EBRixitPI9M1qEhk7VPvu4Jh5g%3D&state=2sXevb_e1wqZpoHUpp9-enftIQLXeD1-mEBoAVhoQ0kHAlpfhwuZwHot02Mj0Rix9nVNSUizk4QqQS2R0X0cddXLtKS_AW42Pn0-Keds7EkeqIKztwuQbGIP5fQERDOGbH80-B0ozXBzjXVATaaWcUNS0iJcBqVSW3PLQRZdwkYgu63VWPivOWE0t7m4M9IHNNuy9IZQ7A&ts=1559569256","req_id":"5af8b523-44fe-b84b-316b-34f958ab81a7","duration":0.0307,"size":19,"status":404,"email":"","group":"","method":"GET","service":"authenticate","url":"/.pomerium","time":"2019-06-03T13:43:15Z","message":"http-request"}
```

### PR DESCRIPTION
**Pull request by desimone**
The existing implementation used a ErrorResponse method to propogate
and create http error messages. Since we added functionality to
troubleshoot, signout, and do other tasks following an http error
it's useful to use Error struct in place of method arguments.

This fixes #157 where a troubleshooting links were appearing on pages
that it didn't make sense on (e.g. pages without valid sessions).

**Checklist**:
- [x] updated docs
- [x] unit tests added
- [x] related issues referenced
- [x] ready for review

### CODE REVIEW

File: internal/httputil/errors.go [hunk 1]
```diff
@@ -10,14 +10,16 @@ import (
...
-// HTTPError stores the status code and a message for a given HTTP error.
-type HTTPError struct {
-	Code    int
-	Message string
+// Error reports an http error, its http status code, a custom message, and
+// whether it is troubleshootable.
+type Error struct {
+	Message          string
+	Code             int
+	Troubleshootable bool
```
Comment (travisgroth) [inline internal/httputil/errors.go]: Nit: Maybe canTroubleshoot or canDebug, unless that term is threaded through the codebase already.
