### PR TITLE
[Backport 0-10-0] proxy: remove impersonate headers for kubernetes

### LINKED ISSUE #1395: backport 1394 to `0-10-0` failed
The backport to `0-10-0` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-0-10-0 0-10-0
# Navigate to the new working tree
cd .worktrees/backport-0-10-0
# Create a new branch
git switch --create backport-1394-to-0-10-0
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick ---mainline 1 a19e45334b96ec6a3c87e6737560f3881918f262
# Push it to GitHub
git push --set-upstream origin backport-1394-to-0-10-0
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-0-10-0
```
Then, create a pull request where the `base` branch is `0-10-0` and the `compare`/`head` branch is `backport-1394-to-0-10-0`.

_Originally posted by @github-actions in https://github.com/pomerium/pomerium/pull/1394#issuecomment-689830187_

### PR DESCRIPTION
**Pull request by travisgroth**
Backport a19e45334b96ec6a3c87e6737560f3881918f262 from #1394

Closes #1395

### CODE REVIEW

File: internal/controlplane/xds_routes_test.go [hunk 1]
```diff
@@ -554,6 +587,65 @@ func Test_buildPolicyRoutesWithDestinationPath(t *testing.T) {
 						{ "enabled": false, "upgradeType": "spdy/3.1"}
 					]
 				}
+<<<<<<< HEAD
```
Comment (calebdoxsey) [inline internal/controlplane/xds_routes_test.go:590]: bad commit?

Comment (travisgroth) [reply internal/controlplane/xds_routes_test.go]: ✅

**Review by calebdoxsey — APPROVED** [review]
