### PR TITLE
autocert: improve logging

### LINKED ISSUE #1749: Autocert debug output
I'm not sure this is really a bug rather than a question on how to diagnose errors with the autocert feature.

## What happened?

I enabled the autocert: true flag in the config.yaml file.

## What did you expect to happen?

I hoped the pomerium system would auto-renew the certificates for the routes in the configuration using lets encrypt. The logging output doesn't really give me a clue as to where the renewal is failing. Is there a way to improve the debug output?

## How'd it happen?

1. Started pomerium
2. Looked at log output
3. Saw this output

## What's your environment like?

- Pomerium 0.11
- Centos/AWS/Docker:
- Log Level is set to debug in environment variables for each docker container
- 
## What's your config.yaml?

```config.yaml
authenticate_service_url: https://auth.example.com

# identity provider settings : https://www.pomerium.io/docs/identity-providers.html

idp_provider: oidc
idp_provider_url: https://idp.example.com
idp_client_id: client-id
idp_client_secret: secret
idp_scopes: openid,profile,email
pomerium_debug: true
autocert: true
autocert_dir: /data/autocert
autocert_use_staging: false
jwt_claims_headers: user
timeout_read: 5m

policy:
  - from: https://test.example.com
    to: https://test.example.com
    tls_custom_ca_file: /pomerium/root_ca.crt
    allowed_idp_claims:
      groups:
        - /support/agents

```

## What did you see in the logs?

```
{"level":"info","domain":"test.example.com","time":"2021-01-07T11:51:26Z","message":"obtaining certificate"}
{"level":"info","time":"2021-01-07T11:51:26Z","logger":"obtain","msg":"acquiring lock","service":"autocert","identifier":"test.example.com"}
{"level":"info","time":"2021-01-07T11:51:26Z","logger":"obtain","msg":"lock acquired","service":"autocert","identifier":"test.example.com"}
2021/01/07 11:51:26 [INFO][FileStorage:/data/autocert] Lock for 'cert_acme_test.example.com_acme-v02.api.letsencrypt.org-directory' is stale (created: 2021-01-07 11:45:51.186740306 +0000 UTC, last update: 2021-01-07 11:51:06.224501391 +0000 UTC); removing then retrying: /data/autocert/locks/cert_acme_test.example.com_acme-v02.api.letsencrypt.org-directory.lock
{"level":"error","time":"2021-01-07T11:51:29Z","logger":"obtain","msg":"will retry","service":"autocert","error":"[test.example.com] Obtain: [test.example.com] solving challenges: test.example.com: no solvers available for remaining challenges (configured=[http-01] offered=[http-01 dns-01 tls-alpn-01] remaining=[dns-01 tls-alpn-01]) (order=https://acme-v02.api.letsencrypt.org/acme/order/1234567/1234567) (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":2.998797907,"max_duration":2592000}
```

Thanks for any advice you may have.

### PR DESCRIPTION
**Pull request by travisgroth**
## Summary
Ensure we're logging acme challenge errors.  Right now we log the failure but not the reason.  Here's an example with this PR:

```
{"level":"error","time":"2021-01-11T15:53:28-05:00","logger":"acme_client","msg":"challenge failed","service":"autocert","identifier":"authenticate.localhost.pomerium.io","challenge_type":"http-01","status_code":400,"problem_type":"urn:ietf:params:acme:error:dns","error":"No valid IP addresses found for authenticate.localhost.pomerium.io"}
```

- internal/autocert: configure logger for acme client
- internal/autocert: don't change certmagic package defaults
- cmd/pomerium: initialize logging before autocert starts
- internal/log: ensure zap logger level matches zerolog level

## Related issues
Closes #1749 

**Checklist**:
- [x] add related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [x] ready for review

### CODE REVIEW

File: internal/autocert/manager.go [hunk 1]
```diff
@@ -92,6 +92,8 @@ func (mgr *Manager) getCertMagicConfig(options *config.Options) (*certmagic.Conf
 			return nil, fmt.Errorf("config: failed caching cert: %w", err)
 		}
 	}
+	// use the same logger as certmagic
+	acmeTemplate.Logger = mgr.certmagic.Logger
```
Comment (calebdoxsey) [inline internal/autocert/manager.go:96]: this is not thread safe. It modifies a global variable.

**Review by calebdoxsey — APPROVED** [review]

File: internal/autocert/manager.go (hunk 1 above)
Comment (travisgroth) [reply internal/autocert/manager.go]: Thanks.  Fixed with a local copy rather than getting rid of the global.   The tests relied on the global acmeTemplate for some setup and I broke them on the first attempt.

**Comment by travisgroth** [comment]
@calebdoxsey this is now properly rebased on top of #1765

**Review by calebdoxsey — APPROVED** [review]
